import type { AIProvider } from './types';

export class MockAIProvider implements AIProvider {
  async generateResponse(prompt: string, _chatHistory: Array<{ role: string; content: string }>): Promise<string> {
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 1000 + Math.random() * 1000));
    
    // Generate a mock response based on the prompt
    const responses = [
      `Here's a helpful response to your question: "${prompt}". This is a mock AI response. In production, this would be generated by the Gemini API.`,
      `Based on your question, I can provide the following insights: This is a simulated response. The actual AI would analyze your prompt and provide relevant content.`,
      `Thank you for your question. Here's a detailed answer: This mock response demonstrates how the AI chat would work with a real provider.`,
    ];
    
    return responses[Math.floor(Math.random() * responses.length)];
  }
}

