import { GoogleGenerativeAI } from '@google/generative-ai';
import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(
  request: VercelRequest,
  response: VercelResponse,
) {
  // Only allow POST requests
  if (request.method !== 'POST') {
    return response.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { prompt, chatHistory } = request.body;

    if (!prompt || typeof prompt !== 'string') {
      return response.status(400).json({ error: 'Prompt is required' });
    }

    // In Vercel serverless functions, env vars are available without VITE_ prefix
    // But we can also access VITE_ prefixed ones
    const apiKey = process.env.VITE_GEMINI_API_KEY || process.env.GEMINI_API_KEY;

    if (!apiKey || apiKey.trim() === '') {
      return response.status(500).json({ 
        error: 'Gemini API key not configured',
        mockResponse: `Here's a helpful response to your question: "${prompt}". This is a mock AI response. In production, this would be generated by the Gemini API.`
      });
    }

    // Initialize Gemini
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-pro' });

    // Convert chat history to Gemini format
    const history = (chatHistory || []).slice(-10).map((msg: { role: string; content: string }) => ({
      role: msg.role === 'student' ? 'user' : 'model',
      parts: [{ text: msg.content }],
    }));

    // Start chat with history
    const chat = model.startChat({
      history: history.length > 0 ? history : undefined,
    });

    // Send message
    const result = await chat.sendMessage(prompt);
    const aiResponse = await result.response;
    const text = aiResponse.text();

    return response.status(200).json({ response: text });
  } catch (error: any) {
    console.error('Gemini API error:', error);
    return response.status(500).json({ 
      error: 'Failed to generate AI response',
      message: error.message || 'Unknown error'
    });
  }
}

