import { GoogleGenerativeAI } from '@google/generative-ai';
import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(
  request: VercelRequest,
  response: VercelResponse,
) {
  // Only allow POST requests
  if (request.method !== 'POST') {
    return response.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { prompt, chatHistory } = request.body;

    if (!prompt || typeof prompt !== 'string') {
      return response.status(400).json({ error: 'Prompt is required' });
    }

    // In Vercel serverless functions, env vars are available without VITE_ prefix
    // But we can also access VITE_ prefixed ones
    const apiKey = process.env.VITE_GEMINI_API_KEY || process.env.GEMINI_API_KEY;

    // Log for debugging (check Vercel function logs)
    console.log('API Key check:', {
      hasViteKey: !!process.env.VITE_GEMINI_API_KEY,
      hasGeminiKey: !!process.env.GEMINI_API_KEY,
      keyLength: apiKey ? apiKey.length : 0
    });

    if (!apiKey || apiKey.trim() === '') {
      console.error('Gemini API key not configured');
      return response.status(500).json({ 
        error: 'Gemini API key not configured',
        mockResponse: `Here's a helpful response to your question: "${prompt}". This is a mock AI response. In production, this would be generated by the Gemini API.`
      });
    }

    // Initialize Gemini
    const genAI = new GoogleGenerativeAI(apiKey);
    
    // Try to get available models first, or use default
    let model;
    try {
      // First, try to list available models to see what's accessible
      // But for now, let's try the default model (no model name specified)
      model = genAI.getGenerativeModel({});
      console.log('Using default Gemini model');
    } catch (e) {
      // If default doesn't work, try common model names
      const modelNames = ['gemini-pro', 'models/gemini-pro', 'gemini-1.5-flash', 'models/gemini-1.5-flash'];
      let modelFound = false;
      
      for (const modelName of modelNames) {
        try {
          model = genAI.getGenerativeModel({ model: modelName });
          console.log(`Using model: ${modelName}`);
          modelFound = true;
          break;
        } catch (err) {
          console.log(`Model ${modelName} not available`);
          continue;
        }
      }
      
      if (!modelFound) {
        throw new Error('No available Gemini models found. Please check your API key and ensure the Generative Language API is enabled.');
      }
    }

    // Convert chat history to Gemini format
    // Filter and ensure first message is from user
    let history = (chatHistory || [])
      .slice(-10)
      .map((msg: { role: string; content: string }) => ({
        role: msg.role === 'student' ? 'user' : 'model',
        parts: [{ text: msg.content }],
      }));

    // Gemini requires first message to be from 'user', not 'model'
    // Remove any leading 'model' messages
    while (history.length > 0 && history[0].role === 'model') {
      history = history.slice(1);
    }

    // If no valid history (all were model messages), use empty history
    if (history.length === 0 || history[0].role !== 'user') {
      history = [];
    }

    // Start chat with history (or without if empty)
    const chat = model.startChat({
      history: history.length > 0 ? history : undefined,
    });

    // Send message
    const result = await chat.sendMessage(prompt);
    const aiResponse = await result.response;
    const text = aiResponse.text();

    return response.status(200).json({ response: text });
  } catch (error: any) {
    console.error('Gemini API error:', error);
    console.error('Error details:', {
      message: error.message,
      status: error.status,
      statusText: error.statusText,
      stack: error.stack
    });
    
    // Return more detailed error information
    return response.status(500).json({ 
      error: 'Failed to generate AI response',
      message: error.message || 'Unknown error',
      details: error.status ? `Status: ${error.status}` : undefined,
      // Include mock response so frontend can still show something
      mockResponse: `I encountered an error: ${error.message || 'Unknown error'}. Please check your API key configuration.`
    });
  }
}

